Add technical review document
PaddlePaddle/Paddle-Inference-Demo pull request #208
Opened 2021-12-26 13:47 UTC by chenyanlann

2021-12-27 07:04 UTC, winter-wang requested changes
请修改所有标题的等级和模板文档的标题等级一致

2021-12-27 07:04 UTC, winter-wang commented on java/飞桨技术评审文档.md
> +<img src="https://pic.imgdb.cn/item/61c9392b2ab3f51d9115d1d3.png" alt="image-20211220100412910" style="zoom: 33%;" />
这个链接直接改为当前路径的相对路径就可以

2021-12-27 07:04 UTC, winter-wang commented on java/飞桨技术评审文档.md
> +<img src="https://pic.imgdb.cn/item/61c9392b2ab3f51d9115d1d9.png" alt="image-20211220100412910" style="zoom: 100%;" />
文件也在该pr中，链接路径改为相对路径就可以，没必要用其它的网址。

2021-12-28 07:02 UTC, Shixiaowei02 commented
请将每个类的实现接口文档也充实到评审文档上，以扩展篇幅。谢谢！

2021-12-28 11:26 UTC, winter-wang approved these changes
LGTM

2022-01-05 08:04 UTC, kolinwei commented
可否贴下使用java api进行预测的相关性能数据,batch_size为1，2，4情况下的平均时延、qps等。

2022-01-18 10:42 UTC, Shixiaowei02 commented
我的建议在方案形成时同步给开发者，我没有其它问题。

2022-01-24 17:18 UTC, chenyanlann commented
@kolinwei 
resnet50模型
输入：batch*3*224*224
CPU：Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
batch 1：0.250 s
batch 2：0.448 s
batch 4：0.731 s
batch 8：1.239 s

2024-02-06 03:13 UTC, closed without merging