Add CPU_Inference docs
PaddlePaddle/Paddle-Inference-Demo pull request #255
Opened 2022-05-23 11:04 UTC by heliqi

2022-05-23 11:21 UTC, jiangjiajun requested changes

2022-05-23 11:21 UTC, jiangjiajun commented on docs-new/cpu_inference/README.md
> +原生CPU推理使用Paddle Inference原生的高性能Kernel进行计算，不依赖第三方加速库。使用部署简单，但性能无优势。
改成：原生CPU推理在推理时，使用飞桨核心框架的标准OP实现进行推理计算，不依赖第三方计算库，推理时也无需额外配置。

2022-05-23 11:21 UTC, jiangjiajun commented on docs-new/cpu_inference/README.md
> +## 使用原生CPU推理
改成：CPU原生推理

2022-05-23 11:21 UTC, jiangjiajun commented on docs-new/cpu_inference/README.md
> +使用原生CPU推理，不同的地方只在配置文件。
删除这句话

2022-05-23 11:21 UTC, jiangjiajun commented on docs-new/cpu_inference/README.md
> +config.set_model("model")
上面是SetModel传入两个文件，下面又变成设置一个模型路径（这种方式在2.0后也并不被推荐，改为与C++一致）

2022-05-23 11:21 UTC, jiangjiajun commented on docs-new/cpu_inference/README.md
> +## 使用MKLDNN推理
改成：MKLDNN推理加速

2022-05-23 11:21 UTC, jiangjiajun commented on docs-new/cpu_inference/README.md
> +MKLDNN是Intel发布的开源的深度学习软件包，Paddle Inference除了有大量的算子支持MKLDNN加速，还针对MKLDNN进行了图优化。
改成： [MKLDNN(现OneDNN)](https://官网)是由英特尔开发的开源深度学习软件包，支持神经网络在CPU上的高性能计算，在Paddle Inference中可通过一行配置打开MKLDNN加速。

2022-05-23 11:21 UTC, jiangjiajun commented on docs-new/cpu_inference/README.md
> +使用MKLDNN推理，只需修改配置文件。
这行也删掉吧

2022-05-23 11:21 UTC, jiangjiajun commented on docs-new/cpu_inference/README.md
> +config.set_model("model")
同上

2022-05-23 11:21 UTC, jiangjiajun commented on docs-new/cpu_inference/README.md
> +## 使用ONNX Runtime后端推理
ONNXRuntime推理

2022-05-23 11:21 UTC, jiangjiajun commented on docs-new/cpu_inference/README.md
> +ONNX Runtime是一个跨平台的机器学习模型加速器，对ONNX标准支持最全最广泛的的推理引擎。Paddle Inference从2.3开始新增了ONNX Runtime后端，能将Paddle模型运行在该后端上。
ONNXRuntime是由微软开源的一款推理引擎，Paddle Inference通过[Paddle2ONNX](https://github.com/PaddlePaddle/Paddle2ONNX)集成ONNXRuntime作为推理的后端之一，开发者在使用时，只需一行配置代码即可让模型通过ONNXRuntime进行推理。

2022-05-23 11:21 UTC, jiangjiajun commented on docs-new/cpu_inference/README.md
> +使用ONNX Runtime推理，只需修改配置文件。
也删除这行

2022-05-23 11:21 UTC, jiangjiajun commented on docs-new/cpu_inference/paddle_x86_cpu_int8.md
>  auto predictor = paddle_infer::CreatePredictor(config);
这里C++代码可视化的缩进不对

2022-05-23 11:31 UTC, heliqi commented on docs-new/cpu_inference/README.md
> +原生CPU推理使用Paddle Inference原生的高性能Kernel进行计算，不依赖第三方加速库。使用部署简单，但性能无优势。
done

2022-05-23 11:32 UTC, heliqi commented on docs-new/cpu_inference/README.md
> +## 使用原生CPU推理
done

2022-05-23 11:33 UTC, heliqi commented on docs-new/cpu_inference/README.md
> +config.set_model("model")
done

2022-05-23 11:34 UTC, heliqi commented on docs-new/cpu_inference/README.md
> +config.set_model("model")
done

2022-05-23 11:35 UTC, heliqi commented on docs-new/cpu_inference/README.md
> +## 使用ONNX Runtime后端推理
done

2022-05-23 11:38 UTC, heliqi commented on docs-new/cpu_inference/README.md
> +ONNX Runtime是一个跨平台的机器学习模型加速器，对ONNX标准支持最全最广泛的的推理引擎。Paddle Inference从2.3开始新增了ONNX Runtime后端，能将Paddle模型运行在该后端上。
done

2022-05-23 11:39 UTC, heliqi commented on docs-new/cpu_inference/README.md
> +使用ONNX Runtime推理，只需修改配置文件。
done

2022-05-23 11:50 UTC, heliqi commented on docs-new/cpu_inference/paddle_x86_cpu_int8.md
>  auto predictor = paddle_infer::CreatePredictor(config);
done

2022-05-23 13:10 UTC, jiangjiajun requested changes

2022-05-23 13:10 UTC, jiangjiajun commented on docs-new/cpu_inference/README.md
> +MKLDNN是Intel发布的开源的深度学习软件包，Paddle Inference除了有大量的算子支持MKLDNN加速，还针对MKLDNN进行了图优化。
这里没改

2022-05-23 14:23 UTC, heliqi commented on docs-new/cpu_inference/README.md
> +MKLDNN是Intel发布的开源的深度学习软件包，Paddle Inference除了有大量的算子支持MKLDNN加速，还针对MKLDNN进行了图优化。
Done

2022-05-23 14:23 UTC, heliqi commented on docs-new/cpu_inference/README.md
> +使用MKLDNN推理，只需修改配置文件。
done

2022-05-24 01:52 UTC, jiangjiajun approved these changes

2022-05-30 09:40 UTC, heliqi commented on docs-new/cpu_inference/README.md
> +Paddle Inference在CPU上有：原生CPU、MKLDNN和ONNX Runtime后端三种推理方式。还支持量化和低精度推理，加快模型推理速度。
这个后端是要针对具体case才能判断出哪个好， 比如有的模型在MKLDNN上运行更快，有些在onnxruntime更快

2022-05-30 09:56 UTC, heliqi commented on docs-new/cpu_inference/paddle_x86_cpu_bf16.md
> +bfloat16 (Brain float Point)浮点格式是一种计算机内存中占用16位的计算机数字格式。该格式是32位IEEE 754单精度浮点格式(float32)的截断(16位)版本，它保留了符号位的1位，指数部分的8位和尾数部分的7位，舍弃了尾数部分不重要的后16位尾数（在float32中，尾数是23位）。Bfloat16用于降低存储需求，提高机器学习算法的计算速度。关于bfloat
done

2022-05-30 10:01 UTC, heliqi commented on docs-new/cpu_inference/paddle_x86_cpu_bf16.md
> +参考[Paddle官网](https://www.paddlepaddle.org.cn/)，安装Paddle最新CPU版本。
done

2022-06-01 05:40 UTC, leiqing1 approved these changes

2022-06-01 13:45 UTC, merged