add NV-GPU
PaddlePaddle/Paddle-Inference-Demo pull request #260
Opened 2022-05-24 11:20 UTC by zhoutianzi666

2022-05-25 12:40 UTC, cyj1986 reviewed
还需要再改改

2022-05-25 12:40 UTC, cyj1986 commented on docs-new/nvidia_jetson_deployment/outline.md
> +GPU 原生推理支持 fp32、int8，fp16 精度目前处于实验阶段。使用前，您需要确保您的机器上已经安装了 CUDA 和 cuDNN。
目前原生推理仅支持fp32， int8 还没有支持

2022-05-25 12:40 UTC, cyj1986 commented on docs-new/nvidia_jetson_deployment/outline.md
> +GPU TensorRT 加速推理需要借助于 TensorRT 软件库，TensorRT 是一个高性能的深度学习预测库，可为深度学习推理应用程序提供低延迟和高吞吐量。Paddle Inference 采用子图的方式对 TensorRT 进行了集成，即我们可以使用该模块来提升 Paddle Inference 的预测性能。TensorRT 接入方式支持 fp32，fp16，int8 精度的推理，除
所有预测， 改为推理； 
软件库， 改为SDK， 遵循 NVIDIA对TensorRT的官方介绍；
第一句话 改为： TensorRT 是一个针对NVIDIA GPU 及Jetson 系列硬件的高性能机器学习推理SDK，可以使得深度学习模型在这些硬件上的部署获得更好的性能；

2022-05-26 04:20 UTC, cyj1986 approved these changes
LGTM

2022-05-26 08:22 UTC, leiqing1 requested changes

2022-05-26 08:22 UTC, leiqing1 commented on docs-new/nvidia_jetson_deployment/gpu_trt_infer.md
> +对于 Jetson 系列硬件上，除了可将模型运行在 GPU 上，Paddle Inference 还开放了启用指定的 DLA 进行模型推理的接口，默认启动第 0 个 DLA：
能简单加一句DLA是什么，在什么场景用，相比在TensorRT的基础上能带来什么效果的描述吗？

2022-05-26 08:22 UTC, leiqing1 commented on docs-new/nvidia_jetson_deployment/gpu_trt_infer.md
> +从1.8 版本开始， Paddle Inference 对 TensorRT 子图进行了 Dynamic shape 的支持。
什么情况/场景下需要用动态shape、动态shape能带来什么好处，简单一句话描述下。

2022-05-26 08:22 UTC, leiqing1 commented on docs-new/nvidia_jetson_deployment/gpu_trt_infer.md
> +## 五：Paddle Inference 子图运行原理
题目是不是改成：
## 五：Paddle Inference 适配TensorRT原理介绍
比较适合？

2022-05-26 08:22 UTC, leiqing1 commented on docs-new/nvidia_jetson_deployment/gpu_fp16_int8.md
> +# 低精度或量化推理
# GPU TensorRT 低精度或量化推理

（如大纲部分我的提问。这部分只有在tensorRT的时候才能使用？那就在题目中说明。我看你正文已经解释了。）

2022-05-26 08:22 UTC, leiqing1 commented on docs-new/nvidia_jetson_deployment/gpu_fp16_int8.md
> +
增加目录

2022-05-27 01:45 UTC, zhoutianzi666 commented on docs-new/nvidia_jetson_deployment/gpu_fp16_int8.md
> +# 低精度或量化推理
已改正

2022-05-27 01:47 UTC, zhoutianzi666 commented on docs-new/nvidia_jetson_deployment/gpu_trt_infer.md
> +## 五：Paddle Inference 子图运行原理
已改正

2022-05-27 01:48 UTC, zhoutianzi666 commented on docs-new/nvidia_jetson_deployment/gpu_trt_infer.md
> +从1.8 版本开始， Paddle Inference 对 TensorRT 子图进行了 Dynamic shape 的支持。
已改正

2022-05-27 01:57 UTC, zhoutianzi666 commented on docs-new/nvidia_jetson_deployment/gpu_trt_infer.md
> +对于 Jetson 系列硬件上，除了可将模型运行在 GPU 上，Paddle Inference 还开放了启用指定的 DLA 进行模型推理的接口，默认启动第 0 个 DLA：
已改正

2022-05-27 02:54 UTC, zhoutianzi666 commented on docs-new/nvidia_jetson_deployment/outline.md
> +本章分为三个部分。
done

2022-05-27 02:54 UTC, zhoutianzi666 commented on docs-new/nvidia_jetson_deployment/outline.md
> +第三部分介绍 Paddle Inference 对低精度和量化推理的支持。
done

2022-05-27 02:59 UTC, zhoutianzi666 commented on docs-new/nvidia_jetson_deployment/gpu_native_infer.md
> +下面分别介绍在 Linux/Ubuntu 操作系统下和 Windows 操作系统下用 GPU 原生推理的 C++ 和 Python 示例。
done

2022-05-27 03:00 UTC, zhoutianzi666 commented on docs-new/nvidia_jetson_deployment/gpu_native_infer.md
> +请参考[下载安装 Ubuntu 推理库](https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#linux)下载 C++ 推理库，名称中带有 `cuda` 的为用于 GPU 的推理库。以 `manylinux_cuda11.2_cudnn8.2_avx_mkl_trt8_gcc8.2`为例，它要求您的系
原生推理和带trt加速的包是同一个包。

2022-05-27 03:00 UTC, zhoutianzi666 commented on docs-new/nvidia_jetson_deployment/gpu_trt_infer.md
> +如果您的机器上已经安装 TensorRT 的话，那么您可以通过 API 启用 TensorRT 加速推理。
done

2022-05-27 03:05 UTC, zhoutianzi666 commented on docs-new/nvidia_jetson_deployment/gpu_fp16_int8.md
> +
done

2022-05-30 02:12 UTC, leiqing1 approved these changes

2022-06-01 05:41 UTC, leiqing1 approved these changes

2022-06-01 09:37 UTC, merged